import type { CompanyType } from '../types/company';
import type { Region } from '../types/common';
import type { Layer } from '../types/layer';
import type { RelationshipType } from '../types/relationship';
import type { TimelineCategory } from '../types/timeline';

export const pricingPowerLabel: Record<Layer['pricingPower'], string> = {
  high: '强',
  medium: '中等',
  low: '较弱',
};

export const pricingPowerUserLabel: Record<Layer['pricingPower'], string> = {
  high: '价格话语权：强',
  medium: '价格话语权：中等',
  low: '价格话语权：较弱',
};

export const pricingPowerDescription: Record<Layer['pricingPower'], string> = {
  high: '该环节对价格和利润影响力强，通常来自稀缺资源、核心技术或客户锁定。',
  medium: '该环节对价格和利润有一定影响力，但仍受市场竞争、成本变化和客户议价影响。',
  low: '该环节更多接受市场价格，利润更容易受上游成本和客户议价影响。',
};

export const policySupportLabel: Record<Layer['chinaLandscape']['policySupport'], string> = {
  strong: '强',
  medium: '中',
  weak: '弱',
};

export const companyTypeLabel: Record<CompanyType, string> = {
  public: '上市公司',
  private: '未上市公司',
  subsidiary: '子公司',
  'state-owned': '国有企业',
  undisclosed: '未披露',
};

export const regionLabel: Record<Region | 'all', string> = {
  all: '全部地区',
  global: '全球',
  china: '中国',
  us: '美国',
  eu: '欧洲',
  asia: '亚洲',
};

export const timelineCategoryLabel: Record<TimelineCategory | 'all', string> = {
  all: '全部主题',
  model: '模型',
  hardware: '硬件',
  infra: '基础设施',
  application: '应用',
  capital: '资本',
  policy: '政策',
};

export const relationshipTypeLabel: Record<RelationshipType, string> = {
  supplier: '供应商',
  customer: '客户',
  competitor: '竞争对手',
  'cloud-partner': '云合作',
  manufacturing: '制造',
  'model-provider': '模型提供方',
  infrastructure: '基础设施',
  investor: '投资方',
  ecosystem: '生态',
};

export const countryLabel: Record<string, string> = {
  CN: '中国',
  US: '美国',
  TW: '中国台湾',
  KR: '韩国',
  JP: '日本',
  NL: '荷兰',
  DE: '德国',
  GB: '英国',
  FR: '法国',
};

const termLabels: Record<string, string> = {
  'AI accelerator': 'AI 加速器',
  'AI clusters': 'AI 集群',
  'AI compute campuses': 'AI 算力园区',
  'AI platform services': 'AI 平台服务',
  'AI research': 'AI 研究',
  'AI safety research': 'AI 安全研究',
  'AI server assembly': 'AI 服务器组装',
  'AI servers': 'AI 服务器',
  'AI systems': 'AI 系统',
  'Advanced nodes': '先进制程',
  'Advanced packaging': '先进封装',
  'Agent framework': '智能体框架',
  'Agent orchestration': '智能体编排',
  'Agent platform': '智能体平台',
  'Analog design': '模拟电路设计',
  'API platform': 'API 平台',
  'Autonomous driving': '自动驾驶',
  'Azure AI': 'Azure AI',
  Bedrock: 'Bedrock',
  'China data centers': '中国数据中心',
  'China/global demand split': '中国与全球需求分化',
  'Chiplet assembly': 'Chiplet 组装',
  Chiplets: 'Chiplet',
  'Claude models': 'Claude 模型',
  'Cloud AI': '云端 AI',
  'Cloud infrastructure manufacturing': '云基础设施制造',
  'Cloud networking': '云网络',
  'Cloud regions': '云区域',
  Colocation: '托管机房',
  'Coater developer': '涂胶显影',
  'Cooling power design': '供电与冷却设计',
  'Copilot UX': 'Copilot 体验',
  'Cortex AI': 'Cortex AI',
  'CPU IP': 'CPU IP',
  'Creative AI': '创意 AI',
  'creative AI': '创意 AI',
  'CRM AI': 'CRM AI',
  'CUDA ecosystem': 'CUDA 生态',
  'CMP slurry': 'CMP 抛光液',
  'Custom AI ASIC': '定制 AI ASIC',
  'Clean firm power': '稳定低碳电力',
  'Data center interconnect': '数据中心互联',
  'Data center platform': '数据中心平台',
  'Data center silicon': '数据中心芯片',
  'Data cloud': '数据云',
  'Data labeling': '数据标注',
  'Deposition': '薄膜沉积',
  'Deposition tools': '沉积设备',
  'Developer Copilot': '开发者 Copilot',
  'Domain datasets': '领域数据集',
  'DRAM stacking': 'DRAM 堆叠',
  'DUV lithography': 'DUV 光刻',
  'EDA software': 'EDA 软件',
  'EDA tools': 'EDA 工具',
  'Edge AI': '边缘 AI',
  'Electronic systems design': '电子系统设计',
  'Embodied models': '具身模型',
  'Enterprise agents': '企业智能体',
  'Enterprise AI factories': '企业 AI 工厂',
  'Enterprise infrastructure': '企业基础设施',
  'Enterprise LLM': '企业级大模型',
  'ERNIE models': '文心大模型',
  'Epitaxial wafers': '外延片',
  'Ethernet fabrics': '以太网组网',
  'Ethernet switches': '以太网交换机',
  'Etch': '刻蚀',
  'Etch equipment': '刻蚀设备',
  'Etch systems': '刻蚀系统',
  'EUV lithography': 'EUV 光刻',
  'Evaluation loops': '评测闭环',
  'EV platform': '电动车平台',
  Filtration: '过滤材料',
  'Fine-tuning': '微调',
  Foundry: '晶圆代工',
  'GAA process': 'GAA 工艺',
  'Gemini models': 'Gemini 模型',
  'Generative media': '生成式媒体',
  'GLM models': 'GLM 模型',
  'GPT models': 'GPT 模型',
  'aesthetic quality': '审美质量',
  brand: '品牌认知',
  community: '创作者社区',
  competition: '竞争加剧',
  copyright: '版权风险',
  'image generation': '图像生成',
  'model cost': '模型成本',
  'Grid infrastructure': '电网基础设施',
  'Grid interconnect': '电网互联',
  'Grid storage': '电网储能',
  'GPU architecture': 'GPU 架构',
  'GPU cloud': 'GPU 云',
  'GPU servers': 'GPU 服务器',
  'HBM interfaces': 'HBM 接口',
  'Humanoid robotics': '人形机器人',
  'Humanoid robots': '人形机器人',
  'Humanoid systems': '人形机器人系统',
  'Hyperscale data centers': '超大规模数据中心',
  'IC substrates': 'IC 载板',
  'Inference chip': '推理芯片',
  'Inference endpoints': '推理端点',
  'Inference optimization': '推理优化',
  'Inference scaling': '推理扩展',
  'Inference systems': '推理系统',
  'Inference ASICs': '推理 ASIC',
  'Interconnect fabric': '互联网络',
  Interconnection: '互联服务',
  Interposers: '中介层',
  'IP cores': 'IP 核',
  'Key investors': '主要投资方',
  Kubernetes: 'Kubernetes',
  Lakehouse: '湖仓平台',
  'Llama models': 'Llama 模型',
  'Logic synthesis': '逻辑综合',
  'Long-context models': '长上下文模型',
  'Long-cycle validation': '长周期验证',
  'Managed hosting': '托管服务',
  'Materials engineering': '材料工程',
  'Mature nodes': '成熟制程',
  Metrology: '量测',
  'Memory controllers': '存储控制器',
  'Memory manufacturing': '存储制造',
  'Mobile AI SoC': '移动 AI SoC',
  'Model hub': '模型社区',
  'Model serving': '模型服务',
  'Multimodal training': '多模态训练',
  'Networking ASIC': '网络 ASIC',
  'Nuclear power': '核电',
  Observability: '可观测性',
  'Office Copilot': 'Office Copilot',
  'Office productivity': '办公效率',
  'Open-weight models': '开放权重模型',
  'OpenAI infrastructure': 'OpenAI 基础设施',
  'Optical modules': '光模块',
  Packaging: '封装',
  'Packaging materials': '封装材料',
  'Photoresist': '光刻胶',
  Planning: '规划算法',
  'Polysilicon': '多晶硅',
  'Power density design': '功率密度设计',
  'Power generation': '发电',
  'Power purchase agreements': '电力采购协议',
  'Process control': '工艺控制',
  'Qianfan platform': '千帆平台',
  'Quadruped robots': '四足机器人',
  'Rack systems': '机架系统',
  'Real-time inference': '实时推理',
  'Renewable energy campuses': '可再生能源园区',
  'Renewable power': '可再生能源',
  'Renewable power equipment': '可再生能源设备',
  'Retail energy': '零售能源',
  'RF process': '射频工艺',
  Robotics: '机器人',
  'Robotics platforms': '机器人平台',
  Robotaxi: '自动驾驶出租车',
  'Sensor fusion': '传感器融合',
  'Service robots': '服务机器人',
  'Silicon wafers': '硅片',
  Silicones: '有机硅',
  'Solar modules': '光伏组件',
  'Specialty chemicals': '特种化学品',
  'Specialty foundry': '特色工艺代工',
  'Specialty gases': '特种气体',
  'Specialty materials': '特种材料',
  Storage: '存储',
  'Storage fabric': '存储网络',
  Substrates: '基板',
  'Test services': '测试服务',
  Testing: '测试',
  'Tongyi platform': '通义平台',
  'Top-tier talent density': '顶尖人才密度',
  'Transformer architectures': 'Transformer 架构',
  'UHV transmission': '特高压输电',
  'Vector retrieval': '向量检索',
  Verification: '验证工具',
  'Vertex AI': 'Vertex AI',
  'Vertical integration': '纵向整合',
  'Wet chemicals': '湿电子化学品',
  'Workflow AI': '工作流 AI',
  'Workflow integration': '工作流集成',
  'Advanced tooling access': '先进工具可得性',
  'AI Native Software': 'AI 原生软件',
};

const normalizedTermLabels = Object.fromEntries(Object.entries(termLabels).map(([term, label]) => [term.toLowerCase(), label]));

export const displayCountry = (country: string) => countryLabel[country] ?? country;

export const displayTerm = (term: string) => termLabels[term] ?? normalizedTermLabels[term.toLowerCase()] ?? term;

export const displayTerms = (terms: string[], separator = ' · ') => terms.map(displayTerm).join(separator);
